server:
  port: 8080

spring:
  application:
    name: ng-service

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.ng.service.entity
